import { describe, it, expect } from 'vitest';
import { ZodError } from 'zod';
import {
  codexSessionCreateSchema,
  codexSessionSendSchema,
  codexSessionListSchema,
  codexSessionForkSchema,
} from '../schemas.js';

describe('codexSessionCreateSchema', () => {
  it('accepts valid input with name', () => {
    const result = codexSessionCreateSchema.parse({ name: 'test', prompt: 'Hello' });
    expect(result.name).toBe('test');
  });

  it('accepts input without name (auto-generated by server)', () => {
    const result = codexSessionCreateSchema.parse({ prompt: 'Hello' });
    expect(result.name).toBeUndefined();
  });

  it('rejects empty name', () => {
    expect(() => codexSessionCreateSchema.parse({ name: '', prompt: 'Hello' })).toThrow(ZodError);
  });

  it('rejects invalid name characters', () => {
    expect(() => codexSessionCreateSchema.parse({ name: 'bad name!', prompt: 'Hello' })).toThrow(ZodError);
  });

  it('rejects missing prompt', () => {
    expect(() => codexSessionCreateSchema.parse({})).toThrow(ZodError);
  });

  it('rejects empty prompt', () => {
    expect(() => codexSessionCreateSchema.parse({ prompt: '' })).toThrow(ZodError);
  });

  it('rejects model with leading dash (flag injection)', () => {
    expect(() => codexSessionCreateSchema.parse({ prompt: 'Hi', model: '--dangerous' })).toThrow(ZodError);
  });

  it('rejects model with shell characters', () => {
    expect(() => codexSessionCreateSchema.parse({ prompt: 'Hi', model: 'model; rm -rf /' })).toThrow(ZodError);
  });

  it('accepts model with dots and hyphens', () => {
    const result = codexSessionCreateSchema.parse({ prompt: 'Hi', model: 'gpt-4.1-mini' });
    expect(result.model).toBe('gpt-4.1-mini');
  });

  it('accepts reasoning_effort enum', () => {
    const result = codexSessionCreateSchema.parse({ prompt: 'Hi', reasoning_effort: 'xhigh' });
    expect(result.reasoning_effort).toBe('xhigh');
  });

  it('rejects invalid reasoning_effort', () => {
    expect(() => codexSessionCreateSchema.parse({ prompt: 'Hi', reasoning_effort: 'max' })).toThrow(ZodError);
  });
});

describe('codexSessionSendSchema', () => {
  it('accepts valid input', () => {
    const result = codexSessionSendSchema.parse({ session: 'my-session', prompt: 'Next' });
    expect(result.session).toBe('my-session');
  });

  it('rejects missing session', () => {
    expect(() => codexSessionSendSchema.parse({ prompt: 'Hello' })).toThrow(ZodError);
  });

  it('accepts working_directory', () => {
    const result = codexSessionSendSchema.parse({
      session: 'my-session',
      prompt: 'Review this',
      working_directory: '/home/user/project',
    });
    expect(result.working_directory).toBe('/home/user/project');
  });

  it('accepts without working_directory (optional)', () => {
    const result = codexSessionSendSchema.parse({
      session: 'my-session',
      prompt: 'Review this',
    });
    expect(result.working_directory).toBeUndefined();
  });
});

describe('codexSessionListSchema', () => {
  it('accepts empty object', () => {
    const result = codexSessionListSchema.parse({});
    expect(result).toEqual({});
  });

  it('rejects unknown properties', () => {
    expect(() => codexSessionListSchema.parse({ extra: true })).toThrow();
  });
});

describe('codexSessionForkSchema', () => {
  it('accepts valid input', () => {
    const result = codexSessionForkSchema.parse({ session: 'abc', prompt: 'Fork this' });
    expect(result.session).toBe('abc');
  });

  it('accepts without optional prompt', () => {
    const result = codexSessionForkSchema.parse({ session: 'abc' });
    expect(result.prompt).toBeUndefined();
  });

  it('rejects invalid fork session name', () => {
    expect(() => codexSessionForkSchema.parse({ session: 'abc', name: 'bad name!' })).toThrow(ZodError);
  });

  it('rejects missing session', () => {
    expect(() => codexSessionForkSchema.parse({})).toThrow(ZodError);
  });

  it('rejects dangerous model in fork', () => {
    expect(() => codexSessionForkSchema.parse({ session: 'abc', model: '$HOME' })).toThrow(ZodError);
  });

  it('accepts working_directory', () => {
    const result = codexSessionForkSchema.parse({
      session: 'abc',
      working_directory: '/home/user/project',
    });
    expect(result.working_directory).toBe('/home/user/project');
  });
});
