export const CLAUDE_CREDENTIAL_ENV_KEYS = Object.freeze([
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_AUTH_TOKEN',
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_CUSTOM_HEADERS',
  'CLAUDE_CODE_OAUTH_TOKEN',
  'CLAUDE_CODE_USE_BEDROCK',
  'CLAUDE_CODE_USE_VERTEX',
  'CLAUDE_CODE_USE_FOUNDRY',
] as const);

export const CLAUDE_PROTECTED_REQUEST_ENV_KEYS = Object.freeze([
  'CLAUDE_CONFIG_DIR',
  ...CLAUDE_CREDENTIAL_ENV_KEYS,
] as const);

export const CLAUDE_ALLOWED_REQUEST_ENV_KEYS = Object.freeze([
  'CORAL_CLAUDE_MODEL_CAP',
  'CORAL_CLAUDE_TRANSPORT',
] as const);

const CLAUDE_CREDENTIAL_ENV_KEY_LOOKUP: ReadonlySet<string> = new Set(CLAUDE_CREDENTIAL_ENV_KEYS);

export function isClaudeCredentialEnvKey(key: string): boolean {
  return CLAUDE_CREDENTIAL_ENV_KEY_LOOKUP.has(key);
}
