export const CLAUDE_CREDENTIAL_ENV_KEYS = Object.freeze(
  new Set([
    'ANTHROPIC_API_KEY',
    'ANTHROPIC_AUTH_TOKEN',
    'ANTHROPIC_BASE_URL',
    'ANTHROPIC_CUSTOM_HEADERS',
    'CLAUDE_CODE_OAUTH_TOKEN',
    'CLAUDE_CODE_USE_BEDROCK',
    'CLAUDE_CODE_USE_VERTEX',
    'CLAUDE_CODE_USE_FOUNDRY',
  ]),
);

export const CLAUDE_PROTECTED_REQUEST_ENV_KEYS = Object.freeze(
  new Set(['CLAUDE_CONFIG_DIR', ...CLAUDE_CREDENTIAL_ENV_KEYS]),
);

export const CLAUDE_ALLOWED_REQUEST_ENV_KEYS = Object.freeze(
  new Set(['CORAL_CLAUDE_MODEL_CAP', 'CORAL_CLAUDE_TRANSPORT']),
);
