// Codex app-server JSON-RPC protocol types.
// Inlined from codex-plugin-cc's app-server-protocol (originally generated by `codex app-server generate-ts`).

import { z } from 'zod';

export interface UserInput {
  type: string;
  text: string;
  text_elements: unknown[];
}

export type NonSteerableTurnKind = 'review' | 'compact';

export type CodexErrorInfo =
  | 'contextWindowExceeded'
  | 'sessionBudgetExceeded'
  | 'usageLimitExceeded'
  | 'serverOverloaded'
  | 'cyberPolicy'
  | 'internalServerError'
  | 'unauthorized'
  | 'badRequest'
  | 'threadRollbackFailed'
  | 'sandboxError'
  | 'other'
  | { httpConnectionFailed: { httpStatusCode: number | null } }
  | { responseStreamConnectionFailed: { httpStatusCode: number | null } }
  | { responseStreamDisconnected: { httpStatusCode: number | null } }
  | { responseTooManyFailedAttempts: { httpStatusCode: number | null } }
  | { activeTurnNotSteerable: { turnKind: NonSteerableTurnKind } };

export interface TurnError {
  message?: string;
  codexErrorInfo?: CodexErrorInfo | null;
  additionalDetails?: string | null;
}

export interface Turn {
  id: string;
  status?: string;
  error?: TurnError | null;
}

interface ThreadInfo {
  id: string;
  name?: string;
  agentNickname?: string;
  agentRole?: string;
}

export interface ThreadStartParams {
  cwd: string;
  model: string | null;
  modelProvider: 'openai';
  approvalPolicy: string;
  sandbox: string;
  serviceTier?: 'default' | 'fast' | 'flex';
  serviceName?: string;
  ephemeral?: boolean;
  config: Readonly<Record<string, unknown>>;
}

export interface ThreadStartResponse {
  thread: ThreadInfo;
  turn?: Turn;
}

export interface ThreadResumeParams {
  threadId: string;
  cwd: string;
  model: string | null;
  modelProvider: 'openai';
  approvalPolicy: string;
  sandbox?: string;
  serviceTier?: 'default' | 'fast' | 'flex';
  config: Readonly<Record<string, unknown>>;
}

interface ThreadResumeResponse {
  thread: ThreadInfo;
}

/** @wire openai:codex — turn/start request body. */
export interface TurnStartParams {
  threadId: string;
  input: UserInput[];
  /** @wire openai:codex — `null` requests the API default model. */
  model?: string | null;
  /** @wire openai:codex — `null` requests the API default effort. */
  effort?: string | null;
  serviceTier?: 'default' | 'fast' | 'flex';
  outputSchema?: unknown;
}

export interface TurnStartResponse {
  turn: Turn;
}

interface TurnInterruptParams {
  threadId: string;
  turnId: string;
}

export const turnInterruptResponseSchema = z.object({}).strict();
type TurnInterruptResponse = z.infer<typeof turnInterruptResponseSchema>;

interface AppServerMethodMap {
  'config/read': {
    params: { includeLayers: false; cwd: string };
    result: { config: Record<string, unknown> };
  };
  'thread/start': { params: ThreadStartParams; result: ThreadStartResponse };
  'thread/resume': { params: ThreadResumeParams; result: ThreadResumeResponse };
  'turn/start': { params: TurnStartParams; result: TurnStartResponse };
  'turn/interrupt': { params: TurnInterruptParams; result: TurnInterruptResponse };
}

export type AppServerMethod = keyof AppServerMethodMap;
export type AppServerRequestParams<M extends AppServerMethod> = AppServerMethodMap[M]['params'];
export type AppServerResponse<M extends AppServerMethod> = AppServerMethodMap[M]['result'];
