// Codex app-server JSON-RPC protocol types.
// Inlined from codex-plugin-cc's app-server-protocol (originally generated by `codex app-server generate-ts`).

export interface UserInput {
  type: string;
  text: string;
  text_elements: unknown[];
}

export interface Turn {
  id: string;
  status?: string;
}

export interface ThreadInfo {
  id: string;
  name?: string;
  agentNickname?: string;
  agentRole?: string;
}

export interface ThreadStartParams {
  cwd: string;
  model: string | null;
  approvalPolicy: string;
  sandbox: string;
  serviceTier?: 'fast' | 'flex';
  serviceName?: string;
  ephemeral?: boolean;
  experimentalRawEvents?: boolean;
}

export interface ThreadStartResponse {
  thread: ThreadInfo;
  turn?: Turn;
}

export interface ThreadResumeParams {
  threadId: string;
  cwd: string;
  model: string | null;
  approvalPolicy: string;
  sandbox?: string;
  serviceTier?: 'fast' | 'flex';
}

export interface ThreadResumeResponse {
  thread: ThreadInfo;
}

export interface TurnStartParams {
  threadId: string;
  input: UserInput[];
  model?: string | null;
  effort?: string | null;
  serviceTier?: 'fast' | 'flex';
  outputSchema?: unknown;
}

export interface TurnStartResponse {
  turn: Turn;
}

export interface TurnInterruptParams {
  threadId: string;
  turnId: string;
}

export interface TurnInterruptResponse {
  threadId: string;
  turnId: string;
}

export interface AppServerMethodMap {
  'thread/start': { params: ThreadStartParams; result: ThreadStartResponse };
  'thread/resume': { params: ThreadResumeParams; result: ThreadResumeResponse };
  'turn/start': { params: TurnStartParams; result: TurnStartResponse };
  'turn/interrupt': { params: TurnInterruptParams; result: TurnInterruptResponse };
}

export type AppServerMethod = keyof AppServerMethodMap;
export type AppServerRequestParams<M extends AppServerMethod> = AppServerMethodMap[M]['params'];
export type AppServerResponse<M extends AppServerMethod> = AppServerMethodMap[M]['result'];
