import type { ZodType } from 'zod';
import {
  equipExpansionRequestSchema,
  listExpansionRequestSchema,
  readBindingRequestSchema,
  unequipExpansionRequestSchema,
} from '../../coordinator/expansion/rpc.js';
import {
  discussSeedSchema,
  discussSessionBidRequestSchema,
  discussSessionCreateRequestSchema,
  discussSessionDeleteRequestSchema,
  discussSessionDetailRequestSchema,
  discussSessionEventsRequestSchema,
  discussSessionListRequestSchema,
  discussSessionSpeechRequestSchema,
} from './discuss.js';
import {
  jobAbortSchema,
  jobDetailRequestSchema,
  jobsListRequestSchema,
  jobWaitSchema,
} from './jobs.js';
import {
  kbCommunityReadRequestSchema,
  kbDiagnoseRequestSchema,
  kbEntriesRequestSchema,
  kbMemoCreateRequestSchema,
  kbMemoDeleteRequestSchema,
  kbMemoListQuerySchema,
  kbMemoReadRequestSchema,
  kbNoteCreateRequestSchema,
  kbNoteDeleteRequestSchema,
  kbNoteReadRequestSchema,
  kbNoteUpdateRequestSchema,
  kbPrincipleReadRequestSchema,
  kbPrinciplesListRequestSchema,
  kbReindexRequestSchema,
  kbSourceCreateRequestSchema,
  kbSourceDeleteRequestSchema,
  kbSourceListRequestSchema,
  kbSourceReadRequestSchema,
} from '../../kb/tool-contracts.js';
import {
  sessionCreateSchema,
  sessionForkRequestSchema,
  sessionMessageRequestSchema,
} from '../../sessions/command-schemas.js';
import type { RpcPorts } from './ports.js';
import { workflowRequestSchema } from './workflow.js';

export interface RpcMethodSpec<Req, _Res> {
  readonly name: string;
  readonly kind: 'unary' | 'subscription';
  readonly requestSchema: ZodType<Req>;
  readonly responseKind: 'json' | 'notification-stream';
  readonly authClass: 'local' | 'authenticated';
  readonly portKey: keyof RpcPorts;
  readonly http: {
    readonly method: 'GET' | 'POST' | 'PUT' | 'DELETE';
    readonly path: string;
    readonly queryShape?: 'bare' | 'keyed';
  };
}

export const transportOperationalCarveouts = ['/health', '/admin/shutdown', '/events/stream'] as const;

export const rpcCatalog = [
  {
    name: 'sessions.create',
    kind: 'unary',
    requestSchema: sessionCreateSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'sessions',
    http: { method: 'POST', path: '/sessions' },
  },
  {
    name: 'sessions.message',
    kind: 'unary',
    requestSchema: sessionMessageRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'sessions',
    http: { method: 'POST', path: '/sessions/:sessionId/messages' },
  },
  {
    name: 'sessions.fork',
    kind: 'unary',
    requestSchema: sessionForkRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'sessions',
    http: { method: 'POST', path: '/sessions/:sessionId/forks' },
  },
  {
    name: 'workflow.run',
    kind: 'unary',
    requestSchema: workflowRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'workflows',
    http: { method: 'POST', path: '/workflow' },
  },
  {
    name: 'coordinator.equipExpansion',
    kind: 'unary',
    requestSchema: equipExpansionRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'expansion',
    http: { method: 'POST', path: '/coordinator/equipment' },
  },
  {
    name: 'coordinator.unequipExpansion',
    kind: 'unary',
    requestSchema: unequipExpansionRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'expansion',
    http: { method: 'DELETE', path: '/coordinator/equipment/:name' },
  },
  {
    name: 'coordinator.listExpansion',
    kind: 'unary',
    requestSchema: listExpansionRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'expansion',
    http: { method: 'GET', path: '/coordinator/equipment' },
  },
  {
    name: 'coordinator.readBinding',
    kind: 'unary',
    requestSchema: readBindingRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'expansion',
    http: { method: 'GET', path: '/coordinator/bindings/:binding' },
  },
  {
    name: 'jobs.abort',
    kind: 'unary',
    requestSchema: jobAbortSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'jobs',
    http: { method: 'POST', path: '/jobs/abort' },
  },
  {
    name: 'jobs.list',
    kind: 'unary',
    requestSchema: jobsListRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'jobs',
    http: { method: 'GET', path: '/jobs', queryShape: 'keyed' },
  },
  {
    name: 'jobs.detail',
    kind: 'unary',
    requestSchema: jobDetailRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'jobs',
    http: { method: 'GET', path: '/jobs/:jobId' },
  },
  {
    name: 'jobs.wait',
    kind: 'subscription',
    requestSchema: jobWaitSchema,
    responseKind: 'notification-stream',
    authClass: 'authenticated',
    portKey: 'jobs',
    http: { method: 'POST', path: '/jobs/wait' },
  },
  {
    name: 'discuss.persona.generate',
    kind: 'unary',
    requestSchema: discussSeedSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/persona-sets' },
  },
  {
    name: 'discuss.session.create',
    kind: 'unary',
    requestSchema: discussSessionCreateRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/sessions' },
  },
  {
    name: 'discuss.session.list',
    kind: 'unary',
    requestSchema: discussSessionListRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'GET', path: '/discuss/sessions' },
  },
  {
    name: 'discuss.session.detail',
    kind: 'unary',
    requestSchema: discussSessionDetailRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'GET', path: '/discuss/sessions/:sessionId', queryShape: 'keyed' },
  },
  {
    name: 'discuss.session.events',
    kind: 'unary',
    requestSchema: discussSessionEventsRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'GET', path: '/discuss/sessions/:sessionId/events', queryShape: 'keyed' },
  },
  {
    name: 'discuss.session.bid',
    kind: 'unary',
    requestSchema: discussSessionBidRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/sessions/:sessionId/bids' },
  },
  {
    name: 'discuss.session.speech',
    kind: 'unary',
    requestSchema: discussSessionSpeechRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/sessions/:sessionId/speeches' },
  },
  {
    name: 'discuss.session.delete',
    kind: 'unary',
    requestSchema: discussSessionDeleteRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'discuss',
    http: { method: 'DELETE', path: '/discuss/sessions/:sessionId', queryShape: 'keyed' },
  },
  {
    name: 'kb.entries.search',
    kind: 'unary',
    requestSchema: kbEntriesRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/entries', queryShape: 'keyed' },
  },
  {
    name: 'kb.diagnose',
    kind: 'unary',
    requestSchema: kbDiagnoseRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/diagnose' },
  },
  {
    name: 'kb.note.read',
    kind: 'unary',
    requestSchema: kbNoteReadRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/notes/:slug' },
  },
  {
    name: 'kb.note.create',
    kind: 'unary',
    requestSchema: kbNoteCreateRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/notes' },
  },
  {
    name: 'kb.note.update',
    kind: 'unary',
    requestSchema: kbNoteUpdateRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'PUT', path: '/kb/notes/:slug' },
  },
  {
    name: 'kb.note.delete',
    kind: 'unary',
    requestSchema: kbNoteDeleteRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'DELETE', path: '/kb/notes/:slug' },
  },
  {
    name: 'kb.source.list',
    kind: 'unary',
    requestSchema: kbSourceListRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/sources' },
  },
  {
    name: 'kb.source.read',
    kind: 'unary',
    requestSchema: kbSourceReadRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/sources/:slug' },
  },
  {
    name: 'kb.source.create',
    kind: 'unary',
    requestSchema: kbSourceCreateRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/sources' },
  },
  {
    name: 'kb.source.delete',
    kind: 'unary',
    requestSchema: kbSourceDeleteRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'DELETE', path: '/kb/sources/:slug' },
  },
  {
    name: 'kb.community.read',
    kind: 'unary',
    requestSchema: kbCommunityReadRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/communities/:slug' },
  },
  {
    name: 'kb.memo.list',
    kind: 'unary',
    requestSchema: kbMemoListQuerySchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/memos', queryShape: 'keyed' },
  },
  {
    name: 'kb.memo.read',
    kind: 'unary',
    requestSchema: kbMemoReadRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/memos/:slug', queryShape: 'keyed' },
  },
  {
    name: 'kb.memo.create',
    kind: 'unary',
    requestSchema: kbMemoCreateRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/memos' },
  },
  {
    name: 'kb.memo.delete',
    kind: 'unary',
    requestSchema: kbMemoDeleteRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'DELETE', path: '/kb/memos', queryShape: 'keyed' },
  },
  {
    name: 'kb.principles.list',
    kind: 'unary',
    requestSchema: kbPrinciplesListRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/principles', queryShape: 'keyed' },
  },
  {
    name: 'kb.principle.read',
    kind: 'unary',
    requestSchema: kbPrincipleReadRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/principles/:slug' },
  },
  {
    name: 'kb.reindex',
    kind: 'unary',
    requestSchema: kbReindexRequestSchema,
    responseKind: 'json',
    authClass: 'authenticated',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/index' },
  },
] as const satisfies readonly RpcMethodSpec<unknown, unknown>[];
