import type { ZodType } from 'zod';
import {
  equipExpansionRequestSchema,
  listExpansionRequestSchema,
  readBindingRequestSchema,
  removeExpansionCatalogRequestSchema,
  unequipExpansionRequestSchema,
} from '../../expansion/rpc-contract.js';
import { discussSeedSchema } from '../../discuss/command-schemas.js';
import {
  discussSessionBidRequestSchema,
  discussSessionCreateRequestSchema,
  discussSessionDeleteRequestSchema,
  discussSessionDetailRequestSchema,
  discussSessionEventsRequestSchema,
  discussSessionListRequestSchema,
  discussSessionSpeechRequestSchema,
} from './discuss.js';
import { jobAbortSchema, jobDetailRequestSchema, jobsListRequestSchema, jobWaitSchema } from './jobs.js';
import {
  kbCommunityReadRequestSchema,
  kbDiagnoseRequestSchema,
  kbEntriesRequestSchema,
  kbMemoCreateRequestSchema,
  kbMemoDeleteRequestSchema,
  kbMemoListQuerySchema,
  kbMemoReadRequestSchema,
  kbNoteCreateRequestSchema,
  kbNoteDeleteRequestSchema,
  kbNoteReadRequestSchema,
  kbNoteUpdateRequestSchema,
  kbPrincipleReadRequestSchema,
  kbPrinciplesListRequestSchema,
  kbReindexRequestSchema,
  kbSourceCreateRequestSchema,
  kbSourceDeleteRequestSchema,
  kbSourceListRequestSchema,
  kbSourceReadRequestSchema,
  kbWakeUpRequestSchema,
  kbWikiAdoptRequestSchema,
  kbWikiCiteRequestSchema,
  kbWikiCreateRequestSchema,
  kbWikiDeleteRequestSchema,
  kbWikiLinkRequestSchema,
  kbWikiListRequestSchema,
  kbWikiReadRequestSchema,
  kbWikiRewriteRequestSchema,
  kbWikiUnlinkRequestSchema,
} from '../../kb/tool-contracts.js';
import { sessionCreateSchema, sessionMessageRequestSchema } from '../../sessions/command-schemas.js';
import type { RpcPorts } from './ports.js';
import { workflowRequestSchema } from './workflow.js';

export interface RpcMethodSpec<Req, _Res> {
  readonly name: string;
  readonly kind: 'unary' | 'subscription';
  readonly requestSchema: ZodType<Req>;
  readonly responseKind: 'json' | 'notification-stream';
  readonly portKey: keyof RpcPorts;
  readonly http: {
    readonly method: 'GET' | 'POST' | 'PUT' | 'DELETE';
    readonly path: string;
    readonly queryShape?: 'bare' | 'keyed';
  };
}

export const transportOperationalCarveouts = ['/health', '/admin/shutdown', '/events/stream'] as const;

export const rpcCatalog = [
  {
    name: 'sessions.create',
    kind: 'unary',
    requestSchema: sessionCreateSchema,
    responseKind: 'json',
    portKey: 'sessions',
    http: { method: 'POST', path: '/sessions' },
  },
  {
    name: 'sessions.message',
    kind: 'unary',
    requestSchema: sessionMessageRequestSchema,
    responseKind: 'json',
    portKey: 'sessions',
    http: { method: 'POST', path: '/sessions/:sessionId/messages' },
  },
  {
    name: 'workflow.run',
    kind: 'unary',
    requestSchema: workflowRequestSchema,
    responseKind: 'json',
    portKey: 'workflows',
    http: { method: 'POST', path: '/workflow' },
  },
  {
    name: 'coordinator.equipExpansion',
    kind: 'unary',
    requestSchema: equipExpansionRequestSchema,
    responseKind: 'json',
    portKey: 'expansion',
    http: { method: 'POST', path: '/coordinator/expansion' },
  },
  {
    name: 'coordinator.unequipExpansion',
    kind: 'unary',
    requestSchema: unequipExpansionRequestSchema,
    responseKind: 'json',
    portKey: 'expansion',
    http: { method: 'DELETE', path: '/coordinator/expansion/:name' },
  },
  {
    name: 'coordinator.removeExpansionCatalog',
    kind: 'unary',
    requestSchema: removeExpansionCatalogRequestSchema,
    responseKind: 'json',
    portKey: 'expansion',
    http: { method: 'DELETE', path: '/coordinator/expansion/:name/catalog' },
  },
  {
    name: 'coordinator.listExpansion',
    kind: 'unary',
    requestSchema: listExpansionRequestSchema,
    responseKind: 'json',
    portKey: 'expansion',
    http: { method: 'GET', path: '/coordinator/expansion' },
  },
  {
    name: 'coordinator.readBinding',
    kind: 'unary',
    requestSchema: readBindingRequestSchema,
    responseKind: 'json',
    portKey: 'expansion',
    http: { method: 'GET', path: '/coordinator/bindings/:binding' },
  },
  {
    name: 'jobs.abort',
    kind: 'unary',
    requestSchema: jobAbortSchema,
    responseKind: 'json',
    portKey: 'jobs',
    http: { method: 'POST', path: '/jobs/abort' },
  },
  {
    name: 'jobs.list',
    kind: 'unary',
    requestSchema: jobsListRequestSchema,
    responseKind: 'json',
    portKey: 'jobs',
    http: { method: 'GET', path: '/jobs', queryShape: 'keyed' },
  },
  {
    name: 'jobs.detail',
    kind: 'unary',
    requestSchema: jobDetailRequestSchema,
    responseKind: 'json',
    portKey: 'jobs',
    http: { method: 'GET', path: '/jobs/:jobId' },
  },
  {
    name: 'jobs.wait',
    kind: 'subscription',
    requestSchema: jobWaitSchema,
    responseKind: 'notification-stream',
    portKey: 'jobs',
    http: { method: 'POST', path: '/jobs/wait' },
  },
  {
    name: 'discuss.persona.generate',
    kind: 'unary',
    requestSchema: discussSeedSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/persona-sets' },
  },
  {
    name: 'discuss.session.create',
    kind: 'unary',
    requestSchema: discussSessionCreateRequestSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/sessions' },
  },
  {
    name: 'discuss.session.list',
    kind: 'unary',
    requestSchema: discussSessionListRequestSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'GET', path: '/discuss/sessions' },
  },
  {
    name: 'discuss.session.detail',
    kind: 'unary',
    requestSchema: discussSessionDetailRequestSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'GET', path: '/discuss/sessions/:sessionId', queryShape: 'keyed' },
  },
  {
    name: 'discuss.session.events',
    kind: 'unary',
    requestSchema: discussSessionEventsRequestSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'GET', path: '/discuss/sessions/:sessionId/events', queryShape: 'keyed' },
  },
  {
    name: 'discuss.session.bid',
    kind: 'unary',
    requestSchema: discussSessionBidRequestSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/sessions/:sessionId/bids' },
  },
  {
    name: 'discuss.session.speech',
    kind: 'unary',
    requestSchema: discussSessionSpeechRequestSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'POST', path: '/discuss/sessions/:sessionId/speeches' },
  },
  {
    name: 'discuss.session.delete',
    kind: 'unary',
    requestSchema: discussSessionDeleteRequestSchema,
    responseKind: 'json',
    portKey: 'discuss',
    http: { method: 'DELETE', path: '/discuss/sessions/:sessionId', queryShape: 'keyed' },
  },
  {
    name: 'kb.entries.search',
    kind: 'unary',
    requestSchema: kbEntriesRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/entries', queryShape: 'keyed' },
  },
  {
    name: 'kb.diagnose',
    kind: 'unary',
    requestSchema: kbDiagnoseRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/diagnose' },
  },
  {
    name: 'kb.note.read',
    kind: 'unary',
    requestSchema: kbNoteReadRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/notes/:slug' },
  },
  {
    name: 'kb.note.create',
    kind: 'unary',
    requestSchema: kbNoteCreateRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/notes' },
  },
  {
    name: 'kb.note.update',
    kind: 'unary',
    requestSchema: kbNoteUpdateRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'PUT', path: '/kb/notes/:slug' },
  },
  {
    name: 'kb.note.delete',
    kind: 'unary',
    requestSchema: kbNoteDeleteRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'DELETE', path: '/kb/notes/:slug' },
  },
  {
    name: 'kb.source.list',
    kind: 'unary',
    requestSchema: kbSourceListRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/sources' },
  },
  {
    name: 'kb.source.read',
    kind: 'unary',
    requestSchema: kbSourceReadRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/sources/:slug' },
  },
  {
    name: 'kb.source.create',
    kind: 'unary',
    requestSchema: kbSourceCreateRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/sources' },
  },
  {
    name: 'kb.source.delete',
    kind: 'unary',
    requestSchema: kbSourceDeleteRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'DELETE', path: '/kb/sources/:slug' },
  },
  {
    name: 'kb.wiki.list',
    kind: 'unary',
    requestSchema: kbWikiListRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/wikis' },
  },
  {
    name: 'kb.wiki.read',
    kind: 'unary',
    requestSchema: kbWikiReadRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/wikis/:slug' },
  },
  {
    name: 'kb.wiki.create',
    kind: 'unary',
    requestSchema: kbWikiCreateRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/wikis' },
  },
  {
    name: 'kb.wiki.rewrite',
    kind: 'unary',
    requestSchema: kbWikiRewriteRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/wikis/:slug/understanding' },
  },
  {
    name: 'kb.wiki.link',
    kind: 'unary',
    requestSchema: kbWikiLinkRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/wikis/:slug/knowledge' },
  },
  {
    name: 'kb.wiki.unlink',
    kind: 'unary',
    requestSchema: kbWikiUnlinkRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/wikis/:slug/knowledge/unlink' },
  },
  {
    name: 'kb.wiki.cite',
    kind: 'unary',
    requestSchema: kbWikiCiteRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/wikis/:slug/knowledge/cite' },
  },
  {
    name: 'kb.wiki.adopt',
    kind: 'unary',
    requestSchema: kbWikiAdoptRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/wikis/:slug/knowledge/adopt' },
  },
  {
    name: 'kb.wiki.delete',
    kind: 'unary',
    requestSchema: kbWikiDeleteRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'DELETE', path: '/kb/wikis/:slug' },
  },
  {
    name: 'kb.wake_up',
    kind: 'unary',
    requestSchema: kbWakeUpRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/wake-up' },
  },
  {
    name: 'kb.community.read',
    kind: 'unary',
    requestSchema: kbCommunityReadRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/communities/:slug' },
  },
  {
    name: 'kb.memo.list',
    kind: 'unary',
    requestSchema: kbMemoListQuerySchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/memos', queryShape: 'keyed' },
  },
  {
    name: 'kb.memo.read',
    kind: 'unary',
    requestSchema: kbMemoReadRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/memos/:slug', queryShape: 'keyed' },
  },
  {
    name: 'kb.memo.create',
    kind: 'unary',
    requestSchema: kbMemoCreateRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/memos' },
  },
  {
    name: 'kb.memo.delete',
    kind: 'unary',
    requestSchema: kbMemoDeleteRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'DELETE', path: '/kb/memos', queryShape: 'keyed' },
  },
  {
    name: 'kb.principles.list',
    kind: 'unary',
    requestSchema: kbPrinciplesListRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/principles', queryShape: 'keyed' },
  },
  {
    name: 'kb.principle.read',
    kind: 'unary',
    requestSchema: kbPrincipleReadRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'GET', path: '/kb/principles/:slug' },
  },
  {
    name: 'kb.reindex',
    kind: 'unary',
    requestSchema: kbReindexRequestSchema,
    responseKind: 'json',
    portKey: 'kb',
    http: { method: 'POST', path: '/kb/index' },
  },
] as const satisfies readonly RpcMethodSpec<unknown, unknown>[];
