export {
  adoptOrphanedCrossNamespaceJobs,
  StartupInterruptedError,
  HANDOFF_DRAIN_TIMEOUT_MS,
  SHUTDOWN_DRAIN_TIMEOUT_MS,
  SHUTDOWN_POLL_MS,
  cleanupStaleJobs,
  closeServer,
  createLifecycle,
  listen,
  markJobsAsError,
  waitForInflightDrain,
} from '../coordinator/control.js';
export type {
  BackendServerInfo,
  BackendIdentity,
  CreateKbSubsystemFn,
  LifecycleController,
  LifecycleDeps,
  LifecycleHooks,
  RecoverPersistedDiscussDeps,
  RecoverPersistedDiscussFn,
  RegisterBuiltInProvidersFn,
  RunStartupRecoveryFn,
  ShutdownMode,
  StartupRecoveryDeps,
} from '../coordinator/control.js';
