export {
  assignEntrySeqs,
  detectRepairs,
  initializeCurateStateIfNeeded,
  persistState,
  reconcileSeqs,
  rewriteFrontmatter,
  scanCorpus,
  syncIndex,
  type CurateBootstrapAssignment,
  type CurateBootstrapScan,
  type CurateBootstrapScanFailure,
  type ScannedNote,
  type ScannedSource,
} from './state-bootstrap.js';
export { readCurateState, writeCurateState } from './state-store.js';
export {
  applyAddPendingDiscovery,
  applyClearCurateRetryState,
  applyRecordCurateFailure,
  applyRecordDiscoveryAttempt,
  applyRemovePendingDiscovery,
  compareCursor,
  compareOptionalCursor,
  defaultCurateState,
  extractMalformedEntryRepair,
  getCurateRepairFrontier,
  isClaimStale,
  normalizeCurateStateRepairFrontier,
  noteCursor,
  readMalformedEntryRepair,
  resetCurateStateForBackfill,
  sameStringList,
  type CurateCursor,
  type CurateRepairFrontier,
  type CurateState,
  type PendingDiscovery,
  type PendingRepair,
} from './state-model.js';
